spring.application.name=Transfer API

spring.datasource.url=jdbc:postgresql://localhost:5432/transferapi
spring.datasource.username=transferapi
spring.datasource.password=transferapi

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.mvc.problemdetails.enabled=true
